# Generated by Django 5.1.7 on 2025-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', unique=True, upload_to='jerseys/'),
        ),
    ]
