# Generated by Django 5.1.6 on 2025-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0004_product_image_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_hash',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', unique=True, upload_to=''),
        ),
    ]
