# Generated by Django 5.1.6 on 2025-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0005_remove_product_image_hash_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='jerseys/'),
        ),
    ]
